apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ujjwal-tekton-testtask
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
    - name: run-test
      image: golang:1.16-alpine
      workingDir: /workspace/repo/src
      command: ["go"]
      args: ["test"]
