apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: testrun
spec:
  taskRef:
    name: ujjwal-tekton-test
  resources:
    inputs:
      - name: repo
        resourceRef:
          name: ujjwal-tekton-taskrunresource