apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ujjwal-tekton-tasktestrun
spec:
  taskRef:
    name: ujjwal-tekton-testtask
  resources:
    inputs:
      - name: repo
        resourceRef:
          name: ujjwal-tekton-gitresource