apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ujjwal-tekton-pipelinetestbuildpush
spec:
  resources:
    - name: repo
      type: git
  tasks:
    # Run application tests
    - name: test
      taskRef:
        name: ujjwal-tekton-testtask
      resources:
        inputs:
          - name: repo
            resource: repo

    # Build docker image and push to registry
    - name: build-and-push
      taskRef:
        name: ujjwal-tekton-buildpushtask
      runAfter:
        - test
      resources:
        inputs:
          - name: repo
            resource: repo
